package Avtek;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Enumeration;
import java.util.concurrent.TimeUnit;
import javax.swing.AbstractButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nace
 */
public class AvtekOkno extends javax.swing.JFrame {

    /**
     * Creates new form AvtekOkno
     */
    public AvtekOkno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gbVelikost = new javax.swing.ButtonGroup();
        gbMenjalnik = new javax.swing.ButtonGroup();
        gbMotor = new javax.swing.ButtonGroup();
        gbPlacilo = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        panelOsnova = new javax.swing.JPanel();
        panelNarocnik = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textFieldIme = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textFieldNaslov = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textFieldKraj = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textFieldEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textFieldTelefon = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        spinnerRojstvo = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jSpinner1 = new javax.swing.JSpinner();
        panelAvto = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        rbMajhen = new javax.swing.JRadioButton();
        rbSrednji = new javax.swing.JRadioButton();
        rbVelik = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        dropMenuModel = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        rbSamodejni = new javax.swing.JRadioButton();
        rbRocni = new javax.swing.JRadioButton();
        rbBencin = new javax.swing.JRadioButton();
        rbDizel = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        rbKartica = new javax.swing.JRadioButton();
        rbGotovina = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        formattedTextKartica = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        formattedTextCCV = new javax.swing.JFormattedTextField();
        bIzracunCena = new javax.swing.JButton();
        labelCena = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        spinnerIzposojaDate = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        spinnerVrnitevDate = new javax.swing.JSpinner();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        spinnerIzposojaHH = new javax.swing.JSpinner();
        jLabel19 = new javax.swing.JLabel();
        spinnerVrnitevHH = new javax.swing.JSpinner();
        jLabel20 = new javax.swing.JLabel();
        dropMenuPrevzem = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        dropMenuOddaja = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        rbZavarovanjeNe = new javax.swing.JRadioButton();
        rbZavarovanjeDa = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuDatoteka = new javax.swing.JMenu();
        menuOdpri = new javax.swing.JMenuItem();
        menuShrani = new javax.swing.JMenuItem();
        menuZapri = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelNarocnik.setBorder(javax.swing.BorderFactory.createTitledBorder("Narocnik"));

        jLabel1.setText("Ime in priimek");

        jLabel2.setText("Naslov");

        jLabel3.setText("Kraj");

        jLabel4.setText("Postna stevilka");

        textFieldKraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldKrajActionPerformed(evt);
            }
        });

        jLabel5.setText("Elektronski naslov");

        jLabel6.setText("Telefonska stevilka");

        textFieldTelefon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldTelefonActionPerformed(evt);
            }
        });

        jLabel7.setText("Datum rojstva");

        spinnerRojstvo.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1605626461155L), null, null, java.util.Calendar.DAY_OF_MONTH));
        spinnerRojstvo.setEditor(new javax.swing.JSpinner.DateEditor(spinnerRojstvo, modelDate.toPattern()));

        jLabel8.setText("Leta vozniskega izpita");

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel());

        javax.swing.GroupLayout panelNarocnikLayout = new javax.swing.GroupLayout(panelNarocnik);
        panelNarocnik.setLayout(panelNarocnikLayout);
        panelNarocnikLayout.setHorizontalGroup(
            panelNarocnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNarocnikLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNarocnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelNarocnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldNaslov)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldKraj, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelNarocnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(spinnerRojstvo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelNarocnikLayout.setVerticalGroup(
            panelNarocnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNarocnikLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNarocnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelNarocnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textFieldNaslov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelNarocnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelNarocnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textFieldKraj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelNarocnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelNarocnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textFieldTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelNarocnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(spinnerRojstvo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelNarocnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelAvto.setBorder(javax.swing.BorderFactory.createTitledBorder("Avto"));

        jLabel9.setText("Velikost");

        gbVelikost.add(rbMajhen);
        rbMajhen.setText("majhen");
        rbMajhen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMajhenActionPerformed(evt);
            }
        });

        gbVelikost.add(rbSrednji);
        rbSrednji.setText("srednji");
        rbSrednji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSrednjiActionPerformed(evt);
            }
        });

        gbVelikost.add(rbVelik);
        rbVelik.setText("velik");
        rbVelik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbVelikActionPerformed(evt);
            }
        });

        jLabel10.setText("Model");

        dropMenuModel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));

        jLabel11.setText("Menjalnik");

        jLabel12.setText("Vrsta motorja");

        gbMenjalnik.add(rbSamodejni);
        rbSamodejni.setText("samodejni");

        gbMenjalnik.add(rbRocni);
        rbRocni.setText("rocni");
        rbRocni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRocniActionPerformed(evt);
            }
        });

        gbMotor.add(rbBencin);
        rbBencin.setText("bencinski");

        gbMotor.add(rbDizel);
        rbDizel.setText("dizelski");
        rbDizel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDizelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAvtoLayout = new javax.swing.GroupLayout(panelAvto);
        panelAvto.setLayout(panelAvtoLayout);
        panelAvtoLayout.setHorizontalGroup(
            panelAvtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAvtoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAvtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(40, 40, 40)
                .addGroup(panelAvtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelAvtoLayout.createSequentialGroup()
                        .addGroup(panelAvtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbMajhen)
                            .addComponent(rbRocni)
                            .addComponent(rbBencin))
                        .addGap(25, 25, 25)
                        .addGroup(panelAvtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbDizel)
                            .addGroup(panelAvtoLayout.createSequentialGroup()
                                .addComponent(rbSrednji)
                                .addGap(25, 25, 25)
                                .addComponent(rbVelik))
                            .addComponent(rbSamodejni)))
                    .addComponent(dropMenuModel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelAvtoLayout.setVerticalGroup(
            panelAvtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAvtoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAvtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(rbMajhen)
                    .addComponent(rbSrednji)
                    .addComponent(rbVelik))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAvtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(dropMenuModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAvtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(rbRocni)
                    .addComponent(rbSamodejni))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAvtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(rbBencin)
                    .addComponent(rbDizel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Placilo"));

        jLabel13.setText("Nacin placila");

        gbPlacilo.add(rbKartica);
        rbKartica.setText("kreditna kartica");
        rbKartica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbKarticaActionPerformed(evt);
            }
        });

        gbPlacilo.add(rbGotovina);
        rbGotovina.setText("gotovina");
        rbGotovina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbGotovinaActionPerformed(evt);
            }
        });

        jLabel14.setText("Stevilka kartice");

        try {
            formattedTextKartica.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####-####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        formattedTextKartica.setEnabled(false);

        jLabel15.setText("CCV");

        try {
            formattedTextCCV.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        formattedTextCCV.setEnabled(false);

        bIzracunCena.setText("Izracun cene izposoje");
        bIzracunCena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIzracunCenaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbKartica, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(formattedTextKartica, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(formattedTextCCV))
                            .addComponent(rbGotovina)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bIzracunCena)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelCena)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(rbKartica)
                    .addComponent(rbGotovina))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(formattedTextKartica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(formattedTextCCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bIzracunCena)
                    .addComponent(labelCena))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Podatki o izposoji"));

        spinnerIzposojaDate.setModel(new javax.swing.SpinnerDateModel());
        spinnerIzposojaDate.setEditor(new javax.swing.JSpinner.DateEditor(spinnerIzposojaDate, modelDate.toPattern()));

        jLabel16.setText("Datum izposoje");

        spinnerVrnitevDate.setModel(new javax.swing.SpinnerDateModel());
        spinnerVrnitevDate.setEditor(new javax.swing.JSpinner.DateEditor(spinnerVrnitevDate, modelDate.toPattern()));

        jLabel17.setText("Datum vrnitve");

        jLabel18.setText("Predvidena ura izposoje");

        spinnerIzposojaHH.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.MINUTE));
        spinnerIzposojaHH.setToolTipText("");
        spinnerIzposojaHH.setEditor(new javax.swing.JSpinner.DateEditor(spinnerIzposojaHH, modelTime.toPattern()));

        jLabel19.setText("Predvidena ura vrnitve");

        spinnerVrnitevHH.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.MINUTE));
        spinnerVrnitevHH.setToolTipText("");
        spinnerVrnitevHH.setEditor(new javax.swing.JSpinner.DateEditor(spinnerVrnitevHH, modelTime.toPattern()));

        jLabel20.setText("Kraj prevzema vozila");

        dropMenuPrevzem.setModel(new javax.swing.DefaultComboBoxModel<>(kraji));

        jLabel21.setText("Kraj oddaje vozila");

        dropMenuOddaja.setModel(new javax.swing.DefaultComboBoxModel<>(kraji));

        jLabel22.setText("Dodatno zavarovanje");

        buttonGroup1.add(rbZavarovanjeNe);
        rbZavarovanjeNe.setSelected(true);
        rbZavarovanjeNe.setText("Ne");

        buttonGroup1.add(rbZavarovanjeDa);
        rbZavarovanjeDa.setText("Da");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(spinnerIzposojaDate, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(61, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spinnerIzposojaHH, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinnerVrnitevDate, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinnerVrnitevHH, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dropMenuPrevzem, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dropMenuOddaja, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rbZavarovanjeDa)
                                .addGap(18, 18, 18)
                                .addComponent(rbZavarovanjeNe)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(spinnerIzposojaDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(spinnerIzposojaHH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(spinnerVrnitevDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(spinnerVrnitevHH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(dropMenuPrevzem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(dropMenuOddaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(rbZavarovanjeDa)
                    .addComponent(rbZavarovanjeNe))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelOsnovaLayout = new javax.swing.GroupLayout(panelOsnova);
        panelOsnova.setLayout(panelOsnovaLayout);
        panelOsnovaLayout.setHorizontalGroup(
            panelOsnovaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOsnovaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelOsnovaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelAvto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelOsnovaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelNarocnik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelOsnovaLayout.setVerticalGroup(
            panelOsnovaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOsnovaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelOsnovaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelNarocnik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelOsnovaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelAvto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelNarocnik.getAccessibleContext().setAccessibleName("Narocnik");
        panelNarocnik.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(panelOsnova, java.awt.BorderLayout.CENTER);

        menuDatoteka.setText("Datoteka");

        menuOdpri.setText("Odpri");
        menuDatoteka.add(menuOdpri);

        menuShrani.setText("Shrani");
        menuDatoteka.add(menuShrani);

        menuZapri.setText("Zapri");
        menuDatoteka.add(menuZapri);

        jMenuBar1.add(menuDatoteka);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbRocniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRocniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbRocniActionPerformed

    private void rbDizelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDizelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbDizelActionPerformed

    private void rbMajhenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMajhenActionPerformed
        dropMenuModel.setModel(new javax.swing.DefaultComboBoxModel<>(smallCars));
    }//GEN-LAST:event_rbMajhenActionPerformed

    private void rbSrednjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSrednjiActionPerformed
        dropMenuModel.setModel(new javax.swing.DefaultComboBoxModel<>(mediumCars));
    }//GEN-LAST:event_rbSrednjiActionPerformed

    private void rbVelikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbVelikActionPerformed
        dropMenuModel.setModel(new javax.swing.DefaultComboBoxModel<>(bigCars));
    }//GEN-LAST:event_rbVelikActionPerformed

    private void rbKarticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbKarticaActionPerformed
        formattedTextKartica.setEnabled(true);
        formattedTextCCV.setEnabled(true);
    }//GEN-LAST:event_rbKarticaActionPerformed

    private void rbGotovinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbGotovinaActionPerformed
        formattedTextKartica.setText("");
        formattedTextCCV.setText("");
        formattedTextKartica.setEnabled(false);
        formattedTextCCV.setEnabled(false);
    }//GEN-LAST:event_rbGotovinaActionPerformed

    private void textFieldTelefonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldTelefonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldTelefonActionPerformed

    private void textFieldKrajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldKrajActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldKrajActionPerformed

    private void bIzracunCenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIzracunCenaActionPerformed
        int cena = 0;
        int diff = 1 + (int) getDateDiff((Date) spinnerIzposojaDate.getValue(), (Date) spinnerVrnitevDate.getValue(), TimeUnit.DAYS);
        if (rbMajhen.isSelected()) {
            cena = 50 * diff;
        } else if (rbSrednji.isSelected()) {
            cena = 80 * diff;
        } else if (rbVelik.isSelected()) {
            cena = 110 * diff;
        }
        
        if (rbBencin.isSelected() || rbDizel.isSelected()) {
            cena += 10 * diff;
        }
        
        if (rbRocni.isSelected() || rbSamodejni.isSelected()) {
            cena += 10 * diff;
        }
        
        if (cena == 0) {
            labelCena.setText("Izberite vse parametre!");
        } else {
            if (rbZavarovanjeDa.isSelected()) {
                cena += 2 * diff;
            }
            labelCena.setText(String.valueOf(cena) + " €");
        }
    }//GEN-LAST:event_bIzracunCenaActionPerformed

    public static long getDateDiff(Date date1, Date date2, TimeUnit timeUnit) {
        long diffInMillies = date2.getTime() - date1.getTime();
        return timeUnit.convert(diffInMillies,TimeUnit.MILLISECONDS);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AvtekOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AvtekOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AvtekOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AvtekOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AvtekOkno().setVisible(true);
            }
        });
    }

    private String[] kraji = new String[] { "Ljubljana", "Maribor", "Celje", "Kranj", "Velenje", "Koper", "Novo mesto", "Murska Sobota", "Jesenice", "Portoroz", "letalisce Brnik", "letalisce Maribor" };
    private SimpleDateFormat modelDate = new SimpleDateFormat("dd/MM/yyyy");
    private SimpleDateFormat modelTime = new SimpleDateFormat("HH:mm");
    private SimpleDateFormat modelYear = new SimpleDateFormat("yyyy");
    private String[] smallCars = new String[] { "Honda Fit", "Mazda 3", "VW Golf", "Toyota Yaris", "Chevrolet Bolt", "MINI Cooper"};
    private String[] mediumCars = new String[] { "MB C180", "Audi A5", "Toyota Avensis", "Honda Accord", "Skoda Octavia" };
    private String[] bigCars = new String[] { "Kia Seltos", "Chevrolet Trailblazer", "VW Atlas", "BMW X6", "Land Rover Defender", "Audi Q3" };
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bIzracunCena;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> dropMenuModel;
    private javax.swing.JComboBox<String> dropMenuOddaja;
    private javax.swing.JComboBox<String> dropMenuPrevzem;
    private javax.swing.JFormattedTextField formattedTextCCV;
    private javax.swing.JFormattedTextField formattedTextKartica;
    private javax.swing.ButtonGroup gbMenjalnik;
    private javax.swing.ButtonGroup gbMotor;
    private javax.swing.ButtonGroup gbPlacilo;
    private javax.swing.ButtonGroup gbVelikost;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel labelCena;
    private javax.swing.JMenu menuDatoteka;
    private javax.swing.JMenuItem menuOdpri;
    private javax.swing.JMenuItem menuShrani;
    private javax.swing.JMenuItem menuZapri;
    private javax.swing.JPanel panelAvto;
    private javax.swing.JPanel panelNarocnik;
    private javax.swing.JPanel panelOsnova;
    private javax.swing.JRadioButton rbBencin;
    private javax.swing.JRadioButton rbDizel;
    private javax.swing.JRadioButton rbGotovina;
    private javax.swing.JRadioButton rbKartica;
    private javax.swing.JRadioButton rbMajhen;
    private javax.swing.JRadioButton rbRocni;
    private javax.swing.JRadioButton rbSamodejni;
    private javax.swing.JRadioButton rbSrednji;
    private javax.swing.JRadioButton rbVelik;
    private javax.swing.JRadioButton rbZavarovanjeDa;
    private javax.swing.JRadioButton rbZavarovanjeNe;
    private javax.swing.JSpinner spinnerIzposojaDate;
    private javax.swing.JSpinner spinnerIzposojaHH;
    private javax.swing.JSpinner spinnerRojstvo;
    private javax.swing.JSpinner spinnerVrnitevDate;
    private javax.swing.JSpinner spinnerVrnitevHH;
    private javax.swing.JTextField textFieldEmail;
    private javax.swing.JTextField textFieldIme;
    private javax.swing.JTextField textFieldKraj;
    private javax.swing.JTextField textFieldNaslov;
    private javax.swing.JTextField textFieldTelefon;
    // End of variables declaration//GEN-END:variables
}
