/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vaje02;

import java.awt.Color;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author nace
 */
public class Vaje02Okvir extends javax.swing.JFrame {

    /**
     * Creates new form Vaje02Okvir
     */
    public Vaje02Okvir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        odpriDialog = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButton1.setText("jButton1");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(jToolBar1, gridBagConstraints);

        jLabel1.setText("Isci");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Zamenjaj");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel1.add(jLabel2, gridBagConstraints);

        jTextField1.setText("Vnesi iskalni niz");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pobrisi2CB(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel1.add(jTextField1, gridBagConstraints);

        jTextField2.setText("Vnesi niz za zamenjavo");
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pobrisiCB(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel1.add(jTextField2, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jLabel3.setText("Status: ");
        getContentPane().add(jLabel3, java.awt.BorderLayout.PAGE_END);

        jTextPane1.setPreferredSize(new java.awt.Dimension(500, 350));
        jScrollPane1.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Datoteka");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setMnemonic('O');
        jMenuItem1.setText("Odpri");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odpriDialogCB(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Shrani");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shraniCB(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Izhod");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Iskanje");

        jMenuItem4.setText("Najdi vse");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                najdiCB(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Zamenjaj vse");
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Barve");

        jMenuItem6.setText("Besedilo");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barvaBesediloCB(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem7.setText("Podlaga");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ozadjeCB(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Pomoc");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void odpriDialogCB(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odpriDialogCB
        int val = odpriDialog.showOpenDialog(this);
        if (val == JFileChooser.APPROVE_OPTION) {
            File f = odpriDialog.getSelectedFile();
            try {
                jTextPane1.read(new FileReader(f), null);
            } catch (Exception e) {}
        }
    }//GEN-LAST:event_odpriDialogCB

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void najdiCB(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_najdiCB
        try {
            String str = jTextPane1.getDocument().getText(0, jTextPane1.getDocument().getLength());
            String isci = jTextField1.getText();
            int i = str.indexOf(isci);
            jTextPane1.select(str.indexOf(isci), str.indexOf(isci) + isci.length());
            jTextPane1.replaceSelection(jTextField2.getText());
            jTextPane1.setCaretPosition(i);
            jTextPane1.grabFocus();
        } catch (Exception e) {}
    }//GEN-LAST:event_najdiCB

    private void pobrisiCB(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pobrisiCB
        jTextField2.setText("");
    }//GEN-LAST:event_pobrisiCB

    private void pobrisi2CB(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pobrisi2CB
        jTextField1.setText("");
    }//GEN-LAST:event_pobrisi2CB

    private void shraniCB(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shraniCB
        int val = odpriDialog.showSaveDialog(this);
        if (val == JFileChooser.APPROVE_OPTION) {
            File f = odpriDialog.getSelectedFile();
            try {
                jTextPane1.write(new FileWriter(f));
            } catch (Exception e) {}
        }
    }//GEN-LAST:event_shraniCB

    private void barvaBesediloCB(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barvaBesediloCB
        Color c = JColorChooser.showDialog(this, "Izberi barvo besedila", Color.yellow);
        StyledDocument sd = jTextPane1.getStyledDocument();
        Style s = jTextPane1.addStyle("Ospredje", null);
        StyleConstants.setForeground(s, c);
        sd.setCharacterAttributes(jTextPane1.getSelectionStart(),
                jTextPane1.getSelectionEnd() - jTextPane1.getSelectionStart(), s, true);
    }//GEN-LAST:event_barvaBesediloCB

    private void ozadjeCB(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ozadjeCB
        Color c = JColorChooser.showDialog(this, "Izberi barvo besedila", Color.yellow);
        StyledDocument sd = jTextPane1.getStyledDocument();
        Style s = jTextPane1.addStyle("Ozadje", null);
        StyleConstants.setBackground(s, c);
        sd.setCharacterAttributes(jTextPane1.getSelectionStart(),
                jTextPane1.getSelectionEnd() - jTextPane1.getSelectionStart(), s, true);
    }//GEN-LAST:event_ozadjeCB

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vaje02Okvir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vaje02Okvir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vaje02Okvir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vaje02Okvir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vaje02Okvir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JFileChooser odpriDialog;
    // End of variables declaration//GEN-END:variables
}
