/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vaje01;

import java.util.ArrayList;
import java.util.List;
import javax.swing.AbstractButton;
import javax.swing.JFileChooser;

/**
 *
 * @author nace
 */
public class Vaje01Okno extends javax.swing.JFrame {

    /**
     * Creates new form Vaje01Okno
     */
    public Vaje01Okno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        mIzpisToolBar1 = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mVpisKraja = new javax.swing.JTextField();
        mIzbiraKraja = new javax.swing.JComboBox<>();
        mRBDodaj = new javax.swing.JRadioButton();
        mRBOdstraniPrvega = new javax.swing.JRadioButton();
        mRBOdstraniIzbranega = new javax.swing.JRadioButton();
        mButtonAkcija = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        mSpinnerPozicija = new javax.swing.JSpinner();
        mCBDvojnik = new javax.swing.JCheckBox();
        mLabelSporocila = new javax.swing.JLabel();
        mMenuBar = new javax.swing.JMenuBar();
        mDatoteke = new javax.swing.JMenu();
        mOdpri = new javax.swing.JMenuItem();
        mPobrisi = new javax.swing.JMenuItem();
        mIzhod = new javax.swing.JMenuItem();
        mIzbire1 = new javax.swing.JMenu();
        mIzbire1N = new javax.swing.JMenuItem();
        mIzbire1A = new javax.swing.JMenuItem();
        mIzbire1C = new javax.swing.JMenuItem();
        mIzbire1E = new javax.swing.JMenuItem();
        mIzbire2 = new javax.swing.JMenu();
        mIzbire2G = new javax.swing.JMenuItem();
        mIzbire2O = new javax.swing.JMenuItem();
        mIzbire2R = new javax.swing.JMenuItem();
        mIzbire2E = new javax.swing.JMenuItem();
        mIzbire2N = new javax.swing.JMenuItem();
        mIzbire2C = new javax.swing.JMenuItem();
        mPomoc = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);
        jToolBar1.add(mIzpisToolBar1);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        status.setText("Status: ");
        getContentPane().add(status, java.awt.BorderLayout.PAGE_END);

        jLabel1.setText("Vpisi kraj");

        mIzbiraKraja.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sentjernej", "Ljubljana", "Novo mesto", "Orehovica" }));
        mIzbiraKraja.setToolTipText("");

        buttonGroup1.add(mRBDodaj);
        mRBDodaj.setSelected(true);
        mRBDodaj.setText("Dodaj");

        buttonGroup1.add(mRBOdstraniPrvega);
        mRBOdstraniPrvega.setText("Odstrani prvega");

        buttonGroup1.add(mRBOdstraniIzbranega);
        mRBOdstraniIzbranega.setText("Odstrani izbranega");

        mButtonAkcija.setText("Izvedi akcijo");
        mButtonAkcija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izvediCB(evt);
            }
        });

        jLabel2.setText("Izberi pozicijo");

        mSpinnerPozicija.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));
        mSpinnerPozicija.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mSpinnerPozicijaStateChanged(evt);
            }
        });

        mCBDvojnik.setText("Prepovej dvojnike");

        mLabelSporocila.setText("Sporocila");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mLabelSporocila, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mVpisKraja)
                            .addComponent(mIzbiraKraja, 0, 264, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mRBDodaj)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(mRBOdstraniPrvega)
                                .addGap(18, 18, 18)
                                .addComponent(mRBOdstraniIzbranega)
                                .addGap(0, 36, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mCBDvojnik)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(mButtonAkcija, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(mSpinnerPozicija, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(mVpisKraja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mIzbiraKraja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mRBDodaj)
                    .addComponent(mRBOdstraniPrvega)
                    .addComponent(mRBOdstraniIzbranega))
                .addGap(18, 18, 18)
                .addComponent(mButtonAkcija)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mSpinnerPozicija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mCBDvojnik)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mLabelSporocila)
                .addGap(0, 60, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        mDatoteke.setMnemonic('D');
        mDatoteke.setText("Datoteka");

        mOdpri.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mOdpri.setMnemonic('O');
        mOdpri.setText("Odpri");
        mOdpri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odpriCB(evt);
            }
        });
        mDatoteke.add(mOdpri);

        mPobrisi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mPobrisi.setMnemonic('P');
        mPobrisi.setText("Pobrisi");
        mPobrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pobrisiCB(evt);
            }
        });
        mDatoteke.add(mPobrisi);

        mIzhod.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mIzhod.setMnemonic('I');
        mIzhod.setText("Izhod");
        mIzhod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IzhodCB(evt);
            }
        });
        mDatoteke.add(mIzhod);

        mMenuBar.add(mDatoteke);

        mIzbire1.setText("Izbire1");

        mIzbire1N.setMnemonic('N');
        mIzbire1N.setText("Izbire1 N");
        mIzbire1N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gumbiCB(evt);
            }
        });
        mIzbire1.add(mIzbire1N);

        mIzbire1A.setMnemonic('A');
        mIzbire1A.setText("Izbire1 A");
        mIzbire1A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gumbiCB(evt);
            }
        });
        mIzbire1.add(mIzbire1A);

        mIzbire1C.setMnemonic('C');
        mIzbire1C.setText("Izbire1 C");
        mIzbire1C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gumbiCB(evt);
            }
        });
        mIzbire1.add(mIzbire1C);

        mIzbire1E.setMnemonic('E');
        mIzbire1E.setText("Izbire1 E");
        mIzbire1E.setDisplayedMnemonicIndex(8);
        mIzbire1E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gumbiCB(evt);
            }
        });
        mIzbire1.add(mIzbire1E);

        mMenuBar.add(mIzbire1);

        mIzbire2.setText("Izbire2");

        mIzbire2G.setMnemonic('G');
        mIzbire2G.setText("Izbire2 G");
        mIzbire2G.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gumbiCB(evt);
            }
        });
        mIzbire2.add(mIzbire2G);

        mIzbire2O.setMnemonic('O');
        mIzbire2O.setText("Izbire2 O");
        mIzbire2O.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gumbiCB(evt);
            }
        });
        mIzbire2.add(mIzbire2O);

        mIzbire2R.setText("Izbire2 R");
        mIzbire2R.setDisplayedMnemonicIndex(8);
        mIzbire2R.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gumbiCB(evt);
            }
        });
        mIzbire2.add(mIzbire2R);

        mIzbire2E.setText("Izbire2 E");
        mIzbire2E.setDisplayedMnemonicIndex(8);
        mIzbire2E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gumbiCB(evt);
            }
        });
        mIzbire2.add(mIzbire2E);

        mIzbire2N.setMnemonic('N');
        mIzbire2N.setText("Izbire2 N");
        mIzbire2N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gumbiCB(evt);
            }
        });
        mIzbire2.add(mIzbire2N);

        mIzbire2C.setMnemonic('C');
        mIzbire2C.setText("Izbire2 C");
        mIzbire2C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gumbiCB(evt);
            }
        });
        mIzbire2.add(mIzbire2C);

        mMenuBar.add(mIzbire2);

        mPomoc.setText("Pomoc");
        mMenuBar.add(mPomoc);

        setJMenuBar(mMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IzhodCB(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IzhodCB
        System.exit(0);
    }//GEN-LAST:event_IzhodCB

    private void gumbiCB(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gumbiCB
        String txt = ((AbstractButton) evt.getSource()).getText();
        status.setText(status.getText() + txt.charAt(txt.length()-1));
        String prevTxt = mIzpisToolBar1.getText();
        mIzpisToolBar1.setText(prevTxt.length() == 0 ? "\"" + txt + "\"": prevTxt + ", \"" + txt + "\"");
    }//GEN-LAST:event_gumbiCB

    private void izvediCB(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izvediCB
        if (mRBDodaj.isSelected()) {
            mLabelSporocila.setText("Sporocila: Dodajam...");
            String txt = mVpisKraja.getText();
            if (txt.length() != 0) {
                boolean lahkoDodam = true;
                for (int i = 0; i < mIzbiraKraja.getItemCount(); i++) {
                    if (txt.equals(mIzbiraKraja.getItemAt(i))) {
                        lahkoDodam = false;
                    }
                }
                if (!mCBDvojnik.isSelected() || lahkoDodam) {
                    mIzbiraKraja.addItem(txt);
                } else {
                    mLabelSporocila.setText("Sporocila: Dvojnik.");
                }
            }
        } else if (mRBOdstraniPrvega.isSelected()) {
            if (mIzbiraKraja.getItemCount() != 0) {
                mLabelSporocila.setText("Sporocila: Brisem prvega...");
                mIzbiraKraja.removeItemAt(0);
            }
        } else {
            if (mIzbiraKraja.getItemCount() != 0) {
                mLabelSporocila.setText("Sporocila: Brisem izbranega...");
                mIzbiraKraja.removeItemAt(mIzbiraKraja.getSelectedIndex());
            }
        }
    }//GEN-LAST:event_izvediCB

    private void odpriCB(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odpriCB
        //Create a file chooser
        final JFileChooser fc = new JFileChooser();
        //In response to a button click:
        int returnVal = fc.showOpenDialog(jPanel1);
    }//GEN-LAST:event_odpriCB

    private void pobrisiCB(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pobrisiCB
        status.setText("Status: ");
        mIzpisToolBar1.setText("");
    }//GEN-LAST:event_pobrisiCB

    private void mSpinnerPozicijaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mSpinnerPozicijaStateChanged
        int p = (int) mSpinnerPozicija.getValue();
        if (mIzbiraKraja.getItemAt(p) != null) {
            mLabelSporocila.setText("Sporocila: " + mIzbiraKraja.getItemAt(p));
        } else {
            mLabelSporocila.setText("Sporocila: Ni elementa");
        }
    }//GEN-LAST:event_mSpinnerPozicijaStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vaje01Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vaje01Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vaje01Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vaje01Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vaje01Okno().setVisible(true);
            }
        });
    }

    private List<String> sporocilaList = new ArrayList<String>();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton mButtonAkcija;
    private javax.swing.JCheckBox mCBDvojnik;
    private javax.swing.JMenu mDatoteke;
    private javax.swing.JComboBox<String> mIzbiraKraja;
    private javax.swing.JMenu mIzbire1;
    private javax.swing.JMenuItem mIzbire1A;
    private javax.swing.JMenuItem mIzbire1C;
    private javax.swing.JMenuItem mIzbire1E;
    private javax.swing.JMenuItem mIzbire1N;
    private javax.swing.JMenu mIzbire2;
    private javax.swing.JMenuItem mIzbire2C;
    private javax.swing.JMenuItem mIzbire2E;
    private javax.swing.JMenuItem mIzbire2G;
    private javax.swing.JMenuItem mIzbire2N;
    private javax.swing.JMenuItem mIzbire2O;
    private javax.swing.JMenuItem mIzbire2R;
    private javax.swing.JMenuItem mIzhod;
    private javax.swing.JLabel mIzpisToolBar1;
    private javax.swing.JLabel mLabelSporocila;
    private javax.swing.JMenuBar mMenuBar;
    private javax.swing.JMenuItem mOdpri;
    private javax.swing.JMenuItem mPobrisi;
    private javax.swing.JMenu mPomoc;
    private javax.swing.JRadioButton mRBDodaj;
    private javax.swing.JRadioButton mRBOdstraniIzbranega;
    private javax.swing.JRadioButton mRBOdstraniPrvega;
    private javax.swing.JSpinner mSpinnerPozicija;
    private javax.swing.JTextField mVpisKraja;
    private javax.swing.JLabel status;
    // End of variables declaration//GEN-END:variables
}
